### ISSUE TITLE
Download is broken !

### ISSUE THREAD

**Issue by Mustapha-Os** [RehabMan/OS-X-ACPI-Backlight#10]
https://bbuseruploads.s3.amazonaws.com/RehabMan/os-x-acpi-backlight/downloads/RehabMan-Backlight-2014-1016.zip?Signature=VJLe++9lZjnNmFlVy19hkA5E5zw=&Expires=1420484512&AWSAccessKeyId=0EMWEFSGA12Z1HF1TZ82 ~ HTTP response : Forbidden !

**Comment by RehabMan** [comment]
Download link is working fine here (it links to bitbucket).  Double check that you're following the link from the README.  And check your internet connection/internet service provider.
