### ISSUE TITLE
new ACPIBacklight is not stable with 10.10-

### ISSUE THREAD

**Issue by dhnguyen92** [RehabMan/OS-X-ACPI-Backlight#14]
The new ACPIBacklight 10.11 causes some problems on many Sandy/Ivy/Haswell laptops when using with 10.10-, some get blackscreen, flickering, unusable brightness. I changed XOPT=0 but it does not help. Install old ACPIBacklight solved the problem.

**Comment by RehabMan** [comment]
No problem here.  Provide ioreg/patchmatic output/etc.  XOPT should be 2 when using new ACPIBacklight.kext.

**Comment by RehabMan** [comment]
I think it is likely people having issues don't have DSDT patched with current patches.
For example, KPCH not being saved in _INI for HD3000/HD4000.

Not sure if the Prebook Installer has kept up on the changes in the patch repos...

**Comment by dhnguyen92** [comment]
HP PBI CE has updated the brightness https://bitbucket.org/dhnguyenit/hp-probook-installer-clover-edition/raw/47610f330fc7972195dd0af610fc54dc7ac0f132/DSDT%20Generator/12_Brightness.txt

I'm sure the Dell Haswell laptop with the problem is patched by the latest brightness patch. Unfortunately I had to return the laptop. But when I get a laptop with the same problem, what info you need me to get for troubleshooting?

**Comment by RehabMan** [comment]
At a minimum, to verify ACPI patches, I would need EFI/Clover folder and ioreg.
I will add some code to deal with missing KPCH (HD3000/HD4000)

**Comment by RehabMan** [comment]
BTW, I think with the new kext and handling backlight changes in the kext instead of ACPI, the brightness changes are smoother, especially in the case of poor displays, such as the stock panel on the 4530s.

**Comment by RehabMan** [comment]
Note: With latest version, XOPT must have bit 1 set (commonly XOPT=2) to use the new code. Otherwise it will use ACPI methods only, even on 10.11.

Watch for it, as it is likely many will not be paying attention and will attempt to run the new version for 10.11 compatibility without proper research and without updating their patched DSDT/SSDT.

**Comment by RehabMan** [comment]
Closing due to lack of requested information.
