### ISSUE TITLE
Brightness reset

### ISSUE THREAD

**Issue by naveen5415** [RehabMan/OS-X-ACPI-Backlight#15]
Hi rehabman . I have Intel hd3000 graphics I patched dsdt and install acpi backlight. Brightness slider works fine but on every reboot brightness lavel reset.

**Comment by RehabMan** [comment]
You need working NVRAM for brightness level restore.

Problem is in your implementation of NVRAM (bootloader issue), not ACPIBacklight.kext.

**Comment by naveenSharma5415** [comment]
Yes, you were right. I installed nvram drivers in clover  and it worked fine in yosemite 10.10.1 but  When I was updated on 10.10.4  the brightness slider disapeared. I do not know what it is
