### ISSUE TITLE
Brightness slider not working el capitan GM

### ISSUE THREAD

**Issue by nveen** [RehabMan/OS-X-ACPI-Backlight#19]
i can see brightness slider but brightness is 100% on 10% -15%.

**Comment by nveen** [comment]
I download latest version it works fine with el capitan.. :) Thank you rehab man....

**Comment by RehabMan** [comment]
Also, see: https://github.com/RehabMan/OS-X-Intel-Backlight

IntelBacklight.kext is the replacement for ACPIBacklight.kext if you have Intel graphics hardware.
