### ISSUE TITLE
ACPIBacklight on Yosemite 10.10 Dell XPS13 - no change in brightness before sleep, flickering after

### ISSUE THREAD

**Issue by JamesCarpenter** [RehabMan/OS-X-ACPI-Backlight#20]
Hi there, 

I've been trying to get ACPIBacklight.kext working with my XPS 13 L321x with limited success. I've done the recommended DSDT brightness patch for HD3000 along with the HD3000_low patch, XPS13 battery patch, Audio layout 3 patch, and GFX0 to IGPU patch. My CPU SSDT is generated using ssdtPRGen.sh and non-CPU SSDTs are extracted using the recommended method in windows and any errors corrected. I am using DropSSDT=Yes and IGPEnabler=No in chameleon.

The trouble that I'm having is that on boot I have no brightness adjustment (AppleBacklight.kext,  AppleBacklightExpert.kext and ACPIBacklight.kext all load, but moving the slider does nothing).  After sleep only ACPIBacklight.kext is loaded and the screen is fine at full brightness, but moving the slider down causes an increasing amount of flickering of the backlight until the minimum value is reached, when things go back to normal again.

Extra folder, as well as patchmatic output and ioreg can be found here: https://drive.google.com/folderview?id=0B38ksJRvnlX0dFVic0ZTeDRkNlE&usp=sharing

kextstat info (after sleep) is here:

users-MacBook-Pro:~ user$ kextstat|grep -y acpiplat
   12    2 0xffffff7f80add000 0x5f000    0x5f000    com.apple.driver.AppleACPIPlatform (3.1) <11 10 7 6 5 4 3 1>
users-MacBook-Pro:~ user$ kextstat|grep -y appleintelcpu
   17    0 0xffffff7f80b78000 0x2b000    0x2b000    com.apple.driver.AppleIntelCPUPowerManagement (218.0.0) <7 6 5 4 3 1>
   28    0 0xffffff7f80c4c000 0x3000     0x3000     com.apple.driver.AppleIntelCPUPowerManagementClient (218.0.0) <7 6 5 4 3 1>

Thanks very much in advance for any help you can offer! Any more info you need just let me know.

Regards,
J

**Comment by RehabMan** [comment]
You can try with KPCH=0 and/or LMAX=0 (read the comments in the patch).

Or you can try using OEM methods for backlight (for the case your laptop doesn't use the IGPU PWM backlight controls).  Use "Brightness Fix" instead.

**Comment by JamesCarpenter** [comment]
Thanks mate - I'll give it a go tonight

**Comment by JamesCarpenter** [comment]
Hi again, I was able to fix the issue by using the "graphics_PNLF-ACPI100.txt" patch instead of the "graphics_PNLF.txt" or "graphics_PNLF_ivy_sandy.txt" one. Brightness now works perfectly! Thanks very much for your help and your work on this, very much appreciated.
