### ISSUE TITLE
Screen Brightness works / Keyboard brightness doesn't

### ISSUE THREAD

**Issue by jagiella** [RehabMan/OS-X-ACPI-Backlight#21]
I use the kext in combination with the brightness patch in SSDT-3.aml. That enables me to change the brightness of my laptop screen, but it doesn't seem to enable brightness control for the backlight of my keyboard. Am I missing out something?

**Comment by RehabMan** [comment]
Your issue has nothing to do with this kext.

http://www.tonymacx86.com/threads/guide-patching-dsdt-ssdt-for-laptop-backlight-control.152659/

**Comment by jagiella** [comment]
Well I applied the patch you uploaded into a forum thread [http://www.tonymacx86.com/threads/asus-g73jh-keyboard-backlighting-working.86141/page-3]((http://www.tonymacx86.com/threads/asus-g73jh-keyboard-backlighting-working.86141/page-3))

**Comment by RehabMan** [comment]
That is not the current technique.  You should read the guide at the first link I provided.

**Comment by ostadsaleh** [comment]
hi rehabman
i have an issue with my enabling keyboard backlight
please tell me step by step how to make ssdt for enabling my keyboard backlight
i am not familiar with ssdt language and every time i used your 07_KeyBacklight.txt i had a lot of errors in vs code
my laptob is asus n550jx and i installed mac os monterey
thanks for your support
