### ISSUE TITLE
Some tips

### ISSUE THREAD

**Issue by felipejfc** [RehabMan/OS-X-ACPI-Backlight#5]
Hi RehabMan, I'm here to share with you how i fixed the kext in my PC (Dell XPS14 L421x)

First I've read the topic
http://www.tonymacx86.com/hp-probook-mavericks/118805-full-range-brightness-using-acpibacklight.html

then i tried to make it working with it instructions, but, it didnt work...

Then I was analising the proposed DSDT patches and I saw that you've put BQC, BCM and BCL in PNLF device, so I've run the Debug mode kext and I saw that it grabbed PNLF as being my IOBacklightDisplay, well it never worked, brightness wont change, so, I took a look at my dsdt and saw that my IGPU dd02 device already had BQC, BCM and BCL methods, so i tought, why not make the kext recognize the correct device to be my gpu, not the PNLF, and then I removed the methods from the PNLF, leaving only this:

```
    Device (PNLF)
    {
        Name (_HID, EisaId ("APP0002"))
        Name (_CID, "backlight")
        Name (_UID, 0x0A)
        Name (_STA, 0x0B)
    }
```

then, I tried to boot again and for my surprise the kext didnt recognize my IGPU dd02 device as my GPU device because it didnt foind the method _BQC on it, in my DSDT BQC is defined as external:

```
External (\_SB_.PCI0.IGPU.DD02._BQC, IntObj)
```

So, I wonder, why would this fail:

```
    if (kIOReturnSuccess == acpiDevice->validateObject("_BQC"))
```

if the method is there? only because its defined as external??

Than i just commented the lines:

```
    /*
    if (kIOReturnSuccess == acpiDevice->validateObject("_BQC"))
        DbgLog("%s: ACPI device %s has _BQC\n", this->getName(), acpiDevice->getName());    
    else
        ret = false;
     */
```

making it not try to find bqc. And then, it worked...

My issues are that the kext can't read the brightness upon start, i get this:

ACPIBacklight: Error in queryACPICurentBrightnessLevel _BQC

And I don't have Smooth brightness 'cause of the lack of xbcm/xbqc...

any tips on this?

I think that maybe fixing this can help you on making the kext compatible with more hacks :)

**Comment by azrak** [comment]
Hi
I have the same laptop i fix it using: 
DD02._BCL ()

**Comment by RehabMan** [comment]
> I have the same laptop i fix it using: DD02._BCL ()

You should not call _BCL from _BQC.  They are not the same thing.  Read the ACPI spec.

**Comment by azrak** [comment]
The Call is not from _BQC
`  Device (PNLF)
            {
                Name (_ADR, Zero)  // _ADR: Address
                Name (_HID, EisaId ("APP0002"))  // _HID: Hardware ID
                Name (_CID, "backlight")  // _CID: Compatible ID
                Name (_UID, 0x0A)  // _UID: Unique ID
                Name (_STA, 0x0B)  // _STA: Status
                Method (_BCM, 1, NotSerialized)  // _BCM: Brightness Control Method
                {
                    ^^DD02._BCM (Arg0)
                }

                Method (_BCL, 0, NotSerialized)  // _BCL: Brightness Control Levels
                {
                    Return (^^DD02._BCL ())
                }

                Method (_DOS, 1, NotSerialized)  // _DOS: Disable Output Switching
                {
                    ^^_DOS (Arg0)
                }

                Method (XBCM, 1, NotSerialized)
                {
                    ^^DD02._BCM (Arg0)
                }

                Method (XBQC, 0, NotSerialized)
                {
                    Return (^^DD02._BCL ())
                }

                Name (XOPT, Zero)
                Method (XRGL, 0, NotSerialized)
                {
                    Store (_BCL (), Local0)
                    Store (DerefOf (Index (Local0, 0x02)), Local0)
                    Return (Local0)
                }

                Method (XRGH, 0, NotSerialized)
                {
                    Store (_BCL (), Local0)
                    Store (DerefOf (Index (Local0, Subtract (SizeOf (Local0), One))), Local0)
                    Return (Local0)
                }
            }
        }
    }`
this work with kernel msg ACPIBacklight: Error in queryACPICurentBrightnessLevel XBQC

**Comment by RehabMan** [comment]
XBQC should not call _BCL.
XBQC is equivalent to _BQC,  not _BCL.
Read the ACPI spec (and ACPIBacklight source).

**Comment by azrak** [comment]
changed to:
`                Method (XBQC, 0, NotSerialized)
                {
                    Return (^^^LPCB.EC0.BRTS)
                }`

**Comment by RehabMan** [comment]
Probably still not correct.
Keep in mind XBQC must return a valid index (into _BCL result) that represents the current brightness level index (as would have been last set with _BCM or XBCM).
You really should read the ACPI spec.

**Comment by azrak** [comment]
I added _BQC Method to DD02 and call it from XBQC whith the same result 
Min Bright at boot & FN Keys Work perfect 
the query_current_brigthness ( _BQC XBQC) method seem do nothing :(
I Atached DSDT + IOREG check it out
[Archive.zip](https://github.com/RehabMan/OS-X-ACPI-Backlight/files/955974/Archive.zip)

**Comment by RehabMan** [comment]
As long as your _BQC method in DD02 is implemented per ACPI spec, there should be no problem.
But returning a constant 0x1e is not correct.
The method should return the current brightness level (last set via _BCM/XBCM).

**Comment by azrak** [comment]
Dell XPs has adaptive brightness controlled by the display firmware
I don't now how this affect .
I tested other patch but this the only that really work 👍
