### ISSUE TITLE
boot with LID closed with external monitor - LCD is dark after open.

### ISSUE THREAD

**Issue by tluck** [RehabMan/OS-X-ACPI-Backlight#8]
don't know if this is an implementation problem or bug... however, with ACPIBacklight.kext installed there is an issue: 

kext installed, boot with LID closed using external monitor. Now open the LID,  the LCD is dark (no image) when Lid is opened. changing the brightness doesn't restore the image - dims the black?
remove ACPIBacklight.kext the screen is OK open opening the Lid after boot-up.

This is on my Lenovo T420 - and another T430 user reported similar issue. thanks for any info or insight as to what  should be changed. my dsdt is posted in the insanely mac T420 forum.

**Comment by RehabMan** [comment]
Closing due to lack of requested information.

**Comment by rajesheber** [comment]
RehabMan,
     Could yo tell me the steps i need to help you with the logs.

**Comment by RehabMan** [comment]
This may be the solution...  For those that have the issue, please try it.

It is described here: http://www.tonymacx86.com/mountain-lion-laptop-support/105027-display-brightness-control-11.html#post1090403

If it works out, I'll change some of the defaults in the patch.

**Comment by tluck** [comment]
yes. cool. this fixed it... on v3.0.3 using method described above. thank you.

**Comment by RehabMan** [comment]
Will keep this open until I decide how to mainstream the fix.

**Comment by RehabMan** [comment]
Here is the solution as linked above...

- install latest ACPIBacklight.kext (because I'm not sure if you're using the latest build)
- in PNLF, edit XOPT so it is 6:
change:
```
            Name (XOPT, Zero)
```
to:
```
            Name (XOPT, 6)
```
- in PNLF, initialize KPCH to -1
change:
```
                Store (PCHL, KPCH)
```
to:
```
                Store (Ones, KPCH)
```

The reason: PCHL is not initialized correctly by BIOS when lid is closed during boot.

**Comment by RehabMan** [comment]
Fixed here: https://github.com/RehabMan/Laptop-DSDT-Patch, commit: https://github.com/RehabMan/Laptop-DSDT-Patch/commit/b6dc06fa7e656a6fc8785bcde87e10dfecc632ee
